# Generated by Django 4.2.6 on 2023-10-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_des', models.TextField()),
                ('location', models.TextField()),
                ('date', models.DateField(default='2023-12-25')),
                ('time', models.TimeField(default='23:00')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.user')),
            ],
        ),
    ]
